# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - app-shir

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: windows-latest
    
    steps:
      - uses: actions/checkout@v4

      - name: Docker login to container registry
        uses: docker/login-action@v2
        with:
          registry: crfeniciadev.azurecr.io/
          username: ${{ secrets.AZUREAPPSERVICE_CONTAINERUSERNAME_C0CA0E296C9A45CB8323DCB48FE42A6D }}
          password: ${{ secrets.AZUREAPPSERVICE_CONTAINERPASSWORD_EE97D31A489844FDBE998481D99F812B }}
          

      - name: Build and Push container to registry
        run: |
          docker build -t crfeniciadev.azurecr.io/shir:${{ github.sha }} .
          docker push crfeniciadev.azurecr.io/shir:${{ github.sha }}
      
      - name: Deploy container to Azure App Service
        uses: Azure/webapps-deploy@v2
        with:
          app-name: 'app-shir'
          slot-name: 'Production'
          images: 'crfeniciadev.azurecr.io/shir:${{ github.sha }}'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_38C13AD5D35A491DAD501CC482591CB7 }}
